version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql 
    ports:
      - "3306:3306"

  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on: 
      - db

  front:
    build: 
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/front
    command: /bin/sh -c "cd react-app && yarn && yarn start"
    ports:
      - "3001:3001"

volumes:
  mysql-data:
